name: Deploy Foam website

on:
  push:

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install website dependencies
        run: npm install
      - name: Build website
        run: npm run build -- --prefix-paths

      - name: Deploy to the gh-pages branch
        # only deploy when the main branch has some changes
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
